/*************************************************************************************************************
Copyright (c) 2012-2015, Symphony Teleca Corporation, a Harman International Industries, Incorporated company
Copyright (c) 2016-2017, Harman International Industries, Incorporated
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS LISTED "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS LISTED BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Attributions: The inih library portion of the source code is licensed from
Brush Technology and Ben Hoyt - Copyright (c) 2009, Brush Technology and Copyright (c) 2009, Ben Hoyt.
Complete license and copyright information can be found at
https://github.com/benhoyt/inih/commit/74d2ca064fb293bc60a77b0bd068075b293cf175.
*************************************************************************************************************/

#ifndef OPENAVB_AECP_CMD_GET_COUNTERS_H
#define OPENAVB_AECP_CMD_GET_COUNTERS_H 1

#include "openavb_aecp.h"

// GET_COUNTERS Command ENTITY Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command AVB_INTERFACE Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_LINK_UP            (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_LINK_DOWN          (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_FRAMES_TX          (8)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_FRAMES_RX          (12)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_RX_CRC_ERROR       (16)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_GPTP_GM_CHANGED    (20)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command CLOCK_DOMAIN Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_LOCKED             (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_UNLOCKED           (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command STREAM_INPUT Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_LOCKED         (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_UNLOCKED       (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_STREAM_RESET         (8)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_SEQ_NUM_MISMATCH     (12)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_RESET          (16)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_UNCERTAIN  (20)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_VALID      (24)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_NOT_VALID  (28)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_UNSUPPORTED_FORMAT   (32)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_LATE_TIMESTAMP       (36)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_EARLY_TIMESTAMP      (40)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_FRAMES_RX            (44)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_FRAMES_TX            (48)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_8    (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_7    (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_6    (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_5    (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_4    (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_3    (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_2    (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_1    (124)


U8 openavbAecpCommandGetCountersHandler(
	openavb_aecp_command_data_get_counters_t *pCmd,
	openavb_aecp_response_data_get_counters_t *pRsp );

#endif // OPENAVB_AECP_CMD_GET_COUNTERS_H
