/*
 ******************************************************************
 * COPYRIGHT (C) Harman International Industries, Inc.
 * All Rights Reserved
 ******************************************************************
 */

#ifndef OPENAVB_AECP_CMD_GET_COUNTERS_H
#define OPENAVB_AECP_CMD_GET_COUNTERS_H 1

#include "openavb_aecp.h"

// GET_COUNTERS Command ENTITY Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_ENTITY_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command AVB_INTERFACE Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_LINK_UP            (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_LINK_DOWN          (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_FRAMES_TX          (8)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_FRAMES_RX          (12)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_RX_CRC_ERROR       (16)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_GPTP_GM_CHANGED    (20)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_AVB_INTERFACE_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command CLOCK_DOMAIN Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_LOCKED             (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_UNLOCKED           (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_8  (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_7  (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_6  (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_5  (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_4  (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_3  (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_2  (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_CLOCK_DOMAIN_OFFSET_ENTITY_SPECIFIC_1  (124)

// GET_COUNTERS Command STREAM_INPUT Counter offsets IEEE Std 1722.1-2013 clause 7.4.42
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_LOCKED         (0)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_UNLOCKED       (4)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_STREAM_RESET         (8)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_SEQ_NUM_MISMATCH     (12)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_MEDIA_RESET          (16)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_UNCERTAIN  (20)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_VALID      (24)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_TIMESTAMP_NOT_VALID  (28)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_UNSUPPORTED_FORMAT   (32)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_LATE_TIMESTAMP       (36)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_EARLY_TIMESTAMP      (40)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_FRAMES_RX            (44)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_FRAMES_TX            (48)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_8    (96)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_7    (100)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_6    (104)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_5    (108)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_4    (112)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_3    (116)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_2    (120)
#define OPENAVB_AEM_GET_COUNTERS_COMMAND_STREAM_INPUT_OFFSET_ENTITY_SPECIFIC_1    (124)


U8 openavbAecpCommandGetCountersHandler(
	openavb_aecp_command_data_get_counters_t *pCmd,
	openavb_aecp_response_data_get_counters_t *pRsp );

#endif // OPENAVB_AECP_CMD_GET_COUNTERS_H
