/*************************************************************************************************************
Copyright (c) 2012-2015, Symphony Teleca Corporation, a Harman International Industries, Incorporated company
Copyright (c) 2016-2017, Harman International Industries, Incorporated
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS LISTED "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS LISTED BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Attributions: The inih library portion of the source code is licensed from
Brush Technology and Ben Hoyt - Copyright (c) 2009, Brush Technology and Copyright (c) 2009, Ben Hoyt.
Complete license and copyright information can be found at
https://github.com/benhoyt/inih/commit/74d2ca064fb293bc60a77b0bd068075b293cf175.
*************************************************************************************************************/

/*
 ******************************************************************
 * MODULE : ADP - AVDECC Discovery Protocol Public Interface
 * MODULE SUMMARY : Public interface for the 1722.1 (AVDECC) discovery protocol
 ******************************************************************
 */

#ifndef OPENAVB_ADP_PUB_H
#define OPENAVB_ADP_PUB_H 1

// message_type field IEEE Std 1722.1-2013 clause 6.2.1.5
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_AVAILABLE (0x00)
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_DEPARTING (0x01)
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_DISCOVER (0x02)

// entity_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.10
#define OPENAVB_ADP_ENTITY_CAPABILITIES_EFU_MODE (0x00000001)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ADDRESS_ACCESS_SUPPORTED (0x00000002)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GATEWAY_ENTITY (0x00000004)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_SUPPORTED (0x00000008)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_LEGACY_AVC (0x00000010)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ASSOCIATION_ID_SUPPORTED (0x00000020)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ASSOCIATION_ID_VALID (0x00000040)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_VENDOR_UNIQUE_SUPPORTED (0x00000080)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_CLASS_A_SUPPORTED (0x00000100)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_CLASS_B_SUPPORTED (0x00000200)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GPTP_SUPPORTED (0x00000400)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_AUTHENTICATION_SUPPORTED (0x00000800)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_AUTHENTICATION_REQUIRED (0x00001000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_PERSISTENT_ACQUIRE_SUPPORTED (0x00002000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_IDENTIFY_CONTROL_INDEX_VALID (0x00004000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_INTERFACE_INDEX_VALID (0x00008000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GENERAL_CONTROLLER_IGNORE (0x00010000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ENTITY_NOT_READY (0x00020000)

// talker_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.12
#define OPENAVB_ADP_TALKER_CAPABILITIES_IMPLEMENTED (0x0001)
#define OPENAVB_ADP_TALKER_CAPABILITIES_OTHER_SOURCE (0x0200)
#define OPENAVB_ADP_TALKER_CAPABILITIES_CONTROL_SOURCE (0x0400)
#define OPENAVB_ADP_TALKER_CAPABILITIES_MEDIA_CLOCK_SOURCE (0x0800)
#define OPENAVB_ADP_TALKER_CAPABILITIES_SMPTE_SOURCE (0x1000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_MIDI_SOURCE (0x2000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_AUDIO_SOURCE (0x4000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_VIDEO_SOURCE (0x8000)

// listener_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.14
#define OPENAVB_ADP_LISTENER_CAPABILITIES_IMPLEMENTED (0x0001)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_OTHER_SINK (0x0200)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_CONTROL_SINK (0x0400)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_MEDIA_CLOCK_SINK (0x0800)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_SMPTE_SINK (0x1000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_MIDI_SINK (0x2000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_AUDIO_SINK (0x4000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_VIDEO_SINK (0x8000)

// controller_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.15
#define OPENAVB_ADP_CONTROLLER_CAPABILITES_IMPLEMENTED (0x00000001)

#endif // OPENAVB_ADP_PUB_H
