/*
 ******************************************************************
 * COPYRIGHT � Symphony Teleca
 *----------------------------------------------------------------*
 * MODULE : ADP - AVDECC Discovery Protocol Public Interface
 *
 * PROGRAMMER : Ken Carlino (Triple Play Integration)
 * DATE :       18-Nov-2013
 * VERSION :    1.0
 *
 *----------------------------------------------------------------*
 *
 * MODULE SUMMARY : Public interface for the 1722.1 (AVDECC) discovery protocol
 *
 *----------------------------------------------------------------*
 *
 * MODIFICATION RECORDS
 *
 ******************************************************************
 */

#ifndef OPENAVB_ADP_PUB_H
#define OPENAVB_ADP_PUB_H 1

// message_type field IEEE Std 1722.1-2013 clause 6.2.1.5
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_AVAILABLE (0x00)
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_DEPARTING (0x01)
#define OPENAVB_ADP_MESSAGE_TYPE_ENTITY_DISCOVER (0x02)

// entity_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.10
#define OPENAVB_ADP_ENTITY_CAPABILITIES_EFU_MODE (0x00000001)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ADDRESS_ACCESS_SUPPORTED (0x00000002)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GATEWAY_ENTITY (0x00000004)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_SUPPORTED (0x00000008)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_LEGACY_AVC (0x00000010)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ASSOCIATION_ID_SUPPORTED (0x00000020)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ASSOCIATION_ID_VALID (0x00000040)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_VENDOR_UNIQUE_SUPPORTED (0x00000080)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_CLASS_A_SUPPORTED (0x00000100)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_CLASS_B_SUPPORTED (0x00000200)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GPTP_SUPPORTED (0x00000400)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_AUTHENTICATION_SUPPORTED (0x00000800)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_AUTHENTICATION_REQUIRED (0x00001000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_PERSISTENT_ACQUIRE_SUPPORTED (0x00002000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_IDENTIFY_CONTROL_INDEX_VALID (0x00004000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_AEM_INTERFACE_INDEX_VALID (0x00008000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_GENERAL_CONTROLLER_IGNORE (0x00010000)
#define OPENAVB_ADP_ENTITY_CAPABILITIES_ENTITY_NOT_READY (0x00020000)

// talker_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.12
#define OPENAVB_ADP_TALKER_CAPABILITIES_IMPLEMENTED (0x0001)
#define OPENAVB_ADP_TALKER_CAPABILITIES_OTHER_SOURCE (0x0200)
#define OPENAVB_ADP_TALKER_CAPABILITIES_CONTROL_SOURCE (0x0400)
#define OPENAVB_ADP_TALKER_CAPABILITIES_MEDIA_CLOCK_SOURCE (0x0800)
#define OPENAVB_ADP_TALKER_CAPABILITIES_SMPTE_SOURCE (0x1000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_MIDI_SOURCE (0x2000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_AUDIO_SOURCE (0x4000)
#define OPENAVB_ADP_TALKER_CAPABILITIES_VIDEO_SOURCE (0x8000)

// listener_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.14
#define OPENAVB_ADP_LISTENER_CAPABILITIES_IMPLEMENTED (0x0001)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_OTHER_SINK (0x0200)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_CONTROL_SINK (0x0400)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_MEDIA_CLOCK_SINK (0x0800)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_SMPTE_SINK (0x1000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_MIDI_SINK (0x2000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_AUDIO_SINK (0x4000)
#define OPENAVB_ADP_LISTENER_CAPABILITIES_VIDEO_SINK (0x8000)

// controller_capabilities field IEEE Std 1722.1-2013 clause 6.2.1.15
#define OPENAVB_ADP_CONTROLLER_CAPABILITES_IMPLEMENTED (0x00000001)

#endif // OPENAVB_ADP_PUB_H
