/*
  Copyright (c) 2013, J.D. Koftinoff Software, Ltd.
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

   1. Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

   3. Neither the name of J.D. Koftinoff Software, Ltd. nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef ADP_H_
#define ADP_H_

/** \addtogroup adp ADP - Clause 6 */
/*@{*/

/** \addtogroup adpdu_msg ADP Message Types - Clause 6.2.1.5 */
/*@{*/
#define ADP_MESSAGE_TYPE_ENTITY_AVAILABLE (0)
#define ADP_MESSAGE_TYPE_ENTITY_DEPARTING (1)
#define ADP_MESSAGE_TYPE_ENTITY_DISCOVER (2)

#define ADP_UNASSIGNED_IPV4 "0.0.0.0"
#define ADP_UNASSIGNED_IPV6 "0::0"
#define ADP_AVDECC_UDP_PORT "17221"
#define ADP_MDNS_MULTICAST_IPV4 "224.0.0.251"
#define ADP_MDNS_MULTICAST_IPV6 "ff02::fb"

/*@}*/

/** \addtogroup adp_entity_capability adp_entity_capability :
 * entity_capabilities field - Clause 6.2.1.10 */
/*@{*/

#define ADP_ENTITY_CAPABILITY_EFU_MODE_BIT (31)
#define ADP_ENTITY_CAPABILITY_EFU_MODE (0x00000001UL)
#define ADP_ENTITY_CAPABILITY_EFU_MODE_MASK (~(0x00000001UL))
#define ADP_ENTITY_CAPABILITY_ADDRESS_ACCESS_SUPPORTED_BIT (30)
#define ADP_ENTITY_CAPABILITY_ADDRESS_ACCESS_SUPPORTED (0x00000002UL)
#define ADP_ENTITY_CAPABILITY_ADDRESS_ACCESS_SUPPORTED_MASK (~(0x00000002UL))
#define ADP_ENTITY_CAPABILITY_GATEWAY_ENTITY_BIT (29)
#define ADP_ENTITY_CAPABILITY_GATEWAY_ENTITY (0x00000004UL)
#define ADP_ENTITY_CAPABILITY_GATEWAY_ENTITY_MASK (~(0x00000004UL))
#define ADP_ENTITY_CAPABILITY_AEM_SUPPORTED_BIT (28)
#define ADP_ENTITY_CAPABILITY_AEM_SUPPORTED (0x00000008UL)
#define ADP_ENTITY_CAPABILITY_AEM_SUPPORTED_MASK (~(0x00000008UL))
#define ADP_ENTITY_CAPABILITY_LEGACY_AVC_BIT (27)
#define ADP_ENTITY_CAPABILITY_LEGACY_AVC (0x00000010UL)
#define ADP_ENTITY_CAPABILITY_LEGACY_AVC_MASK (~(0x00000010UL))
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_SUPPORTED_BIT (26)
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_SUPPORTED (0x00000020UL)
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_SUPPORTED_MASK (~(0x00000020UL))
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_VALID_BIT (25)
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_VALID (0x00000040UL)
#define ADP_ENTITY_CAPABILITY_ASSOCIATION_ID_VALID_MASK (~(0x00000040UL))
#define ADP_ENTITY_CAPABILITY_VENDOR_UNIQUE_SUPPORTED_BIT (24)
#define ADP_ENTITY_CAPABILITY_VENDOR_UNIQUE_SUPPORTED (0x00000080UL)
#define ADP_ENTITY_CAPABILITY_VENDOR_UNIQUE_SUPPORTED_MASK (~(0x00000080UL))
#define ADP_ENTITY_CAPABILITY_CLASS_A_SUPPORTED_BIT (23)
#define ADP_ENTITY_CAPABILITY_CLASS_A_SUPPORTED (0x00000100UL)
#define ADP_ENTITY_CAPABILITY_CLASS_A_SUPPORTED_MASK (~(0x00000100UL))
#define ADP_ENTITY_CAPABILITY_CLASS_B_SUPPORTED_BIT (22)
#define ADP_ENTITY_CAPABILITY_CLASS_B_SUPPORTED (0x00000200UL)
#define ADP_ENTITY_CAPABILITY_CLASS_B_SUPPORTED_MASK (~(0x00000200UL))
#define ADP_ENTITY_CAPABILITY_GPTP_SUPPORTED_BIT (21)
#define ADP_ENTITY_CAPABILITY_GPTP_SUPPORTED (0x00000400UL)
#define ADP_ENTITY_CAPABILITY_GPTP_SUPPORTED_MASK (~(0x00000400UL))
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_SUPPORTED_BIT (20)
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_SUPPORTED (0x00000800UL)
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_SUPPORTED_MASK                \
	(~(0x00000800UL))
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_REQUIRED_BIT (19)
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_REQUIRED (0x00001000UL)
#define ADP_ENTITY_CAPABILITY_AEM_AUTHENTICATION_REQUIRED_MASK (~(0x00001000UL))
#define ADP_ENTITY_CAPABILITY_AEM_PERSISTENT_ACQUIRE_SUPPORTED_BIT (18)
#define ADP_ENTITY_CAPABILITY_AEM_PERSISTENT_ACQUIRE_SUPPORTED (0x00002000UL)
#define ADP_ENTITY_CAPABILITY_AEM_PERSISTENT_ACQUIRE_SUPPORTED_MASK            \
	(~(0x00002000UL))
#define ADP_ENTITY_CAPABILITY_AEM_IDENTIFY_CONTROL_INDEX_VALID_BIT (17)
#define ADP_ENTITY_CAPABILITY_AEM_IDENTIFY_CONTROL_INDEX_VALID (0x00004000UL)
#define ADP_ENTITY_CAPABILITY_AEM_IDENTIFY_CONTROL_INDEX_VALID_MASK            \
	(~(0x00004000UL))
#define ADP_ENTITY_CAPABILITY_AEM_INTERFACE_INDEX_VALID_BIT (16)
#define ADP_ENTITY_CAPABILITY_AEM_INTERFACE_INDEX_VALID (0x00008000UL)
#define ADP_ENTITY_CAPABILITY_AEM_INTERFACE_INDEX_VALID_MASK (~(0x00008000UL))
#define ADP_ENTITY_CAPABILITY_GENERAL_CONTROLLER_IGNORE_BIT (15)
#define ADP_ENTITY_CAPABILITY_GENERAL_CONTROLLER_IGNORE (0x00010000UL)
#define ADP_ENTITY_CAPABILITY_GENERAL_CONTROLLER_IGNORE_MASK (~(0x00010000UL))
#define ADP_ENTITY_CAPABILITY_ENTITY_NOT_READY_BIT (15)
#define ADP_ENTITY_CAPABILITY_ENTITY_NOT_READY (0x00020000UL)
#define ADP_ENTITY_CAPABILITY_ENTITY_NOT_READY_MASK (~(0x00020000UL))

/*@}*/

/** \addtogroup adp_controller_capability adp_controller_capability :
 * adp_controller_capabilities field - Clause 6.2.1.15  */
/*@{*/

#define ADP_CONTROLLER_CAPABILITY_IMPLEMENTED_BIT (31)
#define ADP_CONTROLLER_CAPABILITY_IMPLEMENTED (0x00000001UL)
#define ADP_CONTROLLER_CAPABILITY_IMPLEMENTED_MASK (~(0x00000001UL))

/*@}*/

/** \addtogroup talker_capability talker_capability : talker_capabilities field
 * - Clause 6.2.1.12  */
/*@{*/

#define ADP_TALKER_CAPABILITY_IMPLEMENTED_BIT (15)
#define ADP_TALKER_CAPABILITY_IMPLEMENTED (0x0001)
#define ADP_TALKER_CAPABILITY_IMPLEMENTED_MASK (~0x0001)
#define ADP_TALKER_CAPABILITY_OTHER_SOURCE_BIT (6)
#define ADP_TALKER_CAPABILITY_OTHER_SOURCE (0x0200)
#define ADP_TALKER_CAPABILITY_OTHER_SOURCE_MASK (~0x0200)
#define ADP_TALKER_CAPABILITY_CONTROL_SOURCE_BIT (5)
#define ADP_TALKER_CAPABILITY_CONTROL_SOURCE (0x0400)
#define ADP_TALKER_CAPABILITY_CONTROL_SOURCE_MASK (~0x0400)
#define ADP_TALKER_CAPABILITY_MEDIA_CLOCK_SOURCE_BIT (4)
#define ADP_TALKER_CAPABILITY_MEDIA_CLOCK_SOURCE (0x0800)
#define ADP_TALKER_CAPABILITY_MEDIA_CLOCK_SOURCE_MASK (~0x0800)
#define ADP_TALKER_CAPABILITY_SMPTE_SOURCE_BIT (3)
#define ADP_TALKER_CAPABILITY_SMPTE_SOURCE (0x1000)
#define ADP_TALKER_CAPABILITY_SMPTE_SOURCE_MASK (~0x1000)
#define ADP_TALKER_CAPABILITY_MIDI_SOURCE_BIT (2)
#define ADP_TALKER_CAPABILITY_MIDI_SOURCE (0x2000)
#define ADP_TALKER_CAPABILITY_MIDI_SOURCE_MASK (~0x2000)
#define ADP_TALKER_CAPABILITY_AUDIO_SOURCE_BIT (1)
#define ADP_TALKER_CAPABILITY_AUDIO_SOURCE (0x4000)
#define ADP_TALKER_CAPABILITY_AUDIO_SOURCE_MASK (~0x4000)
#define ADP_TALKER_CAPABILITY_VIDEO_SOURCE_BIT (0)
#define ADP_TALKER_CAPABILITY_VIDEO_SOURCE (0x8000)
#define ADP_TALKER_CAPABILITY_VIDEO_SOURCE_MASK (~0x8000)

/*@}*/

/** \addtogroup adp_listener_capability adp_listener_capability : Listener
 * capabilities field - Clause 6.2.1.14  */
/*@{*/

#define ADP_LISTENER_CAPABILITY_IMPLEMENTED_BIT (15)
#define ADP_LISTENER_CAPABILITY_IMPLEMENTED (0x0001)
#define ADP_LISTENER_CAPABILITY_IMPLEMENTED_MASK (~0x0001)
#define ADP_LISTENER_CAPABILITY_OTHER_SINK_BIT (6)
#define ADP_LISTENER_CAPABILITY_OTHER_SINK (0x0200)
#define ADP_LISTENER_CAPABILITY_OTHER_SINK_MASK (~0x0200)
#define ADP_LISTENER_CAPABILITY_CONTROL_SINK_BIT (5)
#define ADP_LISTENER_CAPABILITY_CONTROL_SINK (0x0400)
#define ADP_LISTENER_CAPABILITY_CONTROL_SINK_MASK (~0x0400)
#define ADP_LISTENER_CAPABILITY_MEDIA_CLOCK_SINK_BIT (4)
#define ADP_LISTENER_CAPABILITY_MEDIA_CLOCK_SINK (0x0800)
#define ADP_LISTENER_CAPABILITY_MEDIA_CLOCK_SINK_MASK (~0x0800)
#define ADP_LISTENER_CAPABILITY_SMPTE_SINK_BIT (3)
#define ADP_LISTENER_CAPABILITY_SMPTE_SINK (0x1000)
#define ADP_LISTENER_CAPABILITY_SMPTE_SINK_MASK (~0x1000)
#define ADP_LISTENER_CAPABILITY_MIDI_SINK_BIT (2)
#define ADP_LISTENER_CAPABILITY_MIDI_SINK (0x2000)
#define ADP_LISTENER_CAPABILITY_MIDI_SINK_MASK (~0x2000)
#define ADP_LISTENER_CAPABILITY_AUDIO_SINK_BIT (1)
#define ADP_LISTENER_CAPABILITY_AUDIO_SINK (0x4000)
#define ADP_LISTENER_CAPABILITY_AUDIO_SINK_MASK (~0x4000)
#define ADP_LISTENER_CAPABILITY_VIDEO_SINK_BIT (0)
#define ADP_LISTENER_CAPABILITY_VIDEO_SINK (0x8000)
#define ADP_LISTENER_CAPABILITY_VIDEO_SINK_MASK (~0x8000)

/*@}*/

/** \addtogroup adpdu ADPDU - Clause 6.2.1 */
/*@{*/

#define ADPDU_OFFSET_ENTITY_MODEL_ID (AVTP_COMMON_CONTROL_HEADER_LEN + 0)
#define ADPDU_OFFSET_ENTITY_CAPABILITIES (AVTP_COMMON_CONTROL_HEADER_LEN + 8)
#define ADPDU_OFFSET_TALKER_STREAM_SOURCES (AVTP_COMMON_CONTROL_HEADER_LEN + 12)
#define ADPDU_OFFSET_TALKER_CAPABILITIES (AVTP_COMMON_CONTROL_HEADER_LEN + 14)
#define ADPDU_OFFSET_LISTENER_STREAM_SINKS (AVTP_COMMON_CONTROL_HEADER_LEN + 16)
#define ADPDU_OFFSET_LISTENER_CAPABILITIES (AVTP_COMMON_CONTROL_HEADER_LEN + 18)
#define ADPDU_OFFSET_CONTROLLER_CAPABILITIES                                   \
    (AVTP_COMMON_CONTROL_HEADER_LEN + 20)
#define ADPDU_OFFSET_AVAILABLE_INDEX (AVTP_COMMON_CONTROL_HEADER_LEN + 24)
#define ADPDU_OFFSET_GPTP_GRANDMASTER_ID (AVTP_COMMON_CONTROL_HEADER_LEN + 28)
#define ADPDU_OFFSET_GPTP_DOMAIN_NUMBER (AVTP_COMMON_CONTROL_HEADER_LEN + 36)
#define ADPDU_OFFSET_RESERVED0 (AVTP_COMMON_CONTROL_HEADER_LEN + 37)
#define ADPDU_OFFSET_IDENTIFY_CONTROL_INDEX                                    \
    (AVTP_COMMON_CONTROL_HEADER_LEN + 40)
#define ADPDU_OFFSET_INTERFACE_INDEX (AVTP_COMMON_CONTROL_HEADER_LEN + 42)
#define ADPDU_OFFSET_ASSOCIATION_ID (AVTP_COMMON_CONTROL_HEADER_LEN + 44)
#define ADPDU_OFFSET_RESERVED1 (AVTP_COMMON_CONTROL_HEADER_LEN + 52)
#define ADPDU_LEN (AVTP_COMMON_CONTROL_HEADER_LEN + 56)

/*@}*/



#endif /* ADP_H_ */
